### ISSUE TITLE
Overflow of numbers in screen

### ISSUE THREAD

**Issue by Viv-Dave** [mathdebate09/calculator#1]
Numbers overflow out of the screen when entered repetitively.

**Comment by mathdebate09** [comment]
an overflow:hidden should do the work but I'm too bored to do it ;-;

**Comment by mathdebate09** [comment]
Issue resolved [2e2b309](https://github.com/mathdebate09/calculator/commit/2e2b30999925fb3a492df71b0654fd5bcfe26f52)
